/// Simplified Chinese language pack.
///
/// The keys are the Hungarian source strings used by the upstream app.  Keeping the
/// pack in its own file makes it easy to carry forward when upstream changes the UI.
/// Terminology follows the Simplified Chinese translation in the original transgui
/// project where the concepts overlap.
let simplifiedChineseStrings: [String: String] = [
    // General actions and errors
    "Hozzáadás": "添加",
    "Indítás": "开始",
    "Leállítás": "停止",
    "Törlés": "删除",
    "Frissítés": "刷新",
    "Szerkesztés": "编辑",
    "Csatlakozás": "连接",
    "Mégse": "取消",
    "Mentés": "保存",
    "Részletek": "详细信息",
    "Keresés": "搜索",
    // Client-only path mapping and Finder reveal
    "Megjelenítés a Finderben": "在 Finder 中显示",
    "Útvonal-hozzárendelések": "路径映射",
    "Távoli mappa": "远程文件夹",
    "Helyi mappa": "本地文件夹",
    "Új hozzárendelés": "添加映射",
    "Hozzárendelés eltávolítása": "移除映射",
    "Beillesztés…": "粘贴映射…",
    "Importálás": "导入",
    "Távoli útvonal=helyi útvonal, soronként egy.": "远程路径=本地路径，每行一条映射。",
    "Csak a helyi Finder-megjelenítést érinti. A megosztásokat előbb kézzel csatold.": "仅用于在 Finder 中显示。请先手动挂载共享文件夹。",
    "Adj meg abszolút távoli és helyi mappákat; a . és .. nem engedélyezett.": "请输入远程和本地文件夹的绝对路径；不允许使用 . 或 ..。",
    "Egy távoli mappához csak egy hozzárendelés tartozhat.": "每个远程文件夹只能配置一条映射。",
    "Érvénytelen fájlútvonal érkezett a szervertől.": "服务器返回的文件路径无效。",
    "Nincs illeszkedő útvonal-hozzárendelés. Állítsd be a Beállítások → Szerverek → Szerkesztés alatt.": "没有匹配的路径映射。请前往“设置 → 服务器 → 编辑”配置。",
    "A torrent fájllistája még nem érhető el.": "尚未取得种子的文件列表。",
    "A torrent megváltozott vagy már nem található. Próbáld újra.": "种子已发生变化或不存在，请重试。",
    "A helyi kötet nincs csatolva. Csatold a megosztást a Finderben.": "本地卷尚未挂载，请先在 Finder 中连接共享文件夹。",
    "A hozzárendelt fájl vagy mappa nem található.": "映射后的文件或文件夹不存在。",
    "A hozzárendelt útvonal nem olvasható. Ellenőrizd a jogosultságokat.": "无法读取映射后的路径，请检查访问权限。",
    "Az útvonal a hozzárendelt mappán kívülre mutat.": "该路径指向映射文件夹以外的位置。",
    "A helyi megosztás nem válaszolt időben. Ellenőrizd a kapcsolatot, majd próbáld újra.": "本地共享文件夹响应超时，请检查连接后重试。",
    "Érvénytelen szerver URL.": "服务器 URL 无效。",
    "Hálózati hiba:": "网络错误：",
    "HTTP hiba:": "HTTP 错误：",
    "Hibás felhasználónév vagy jelszó.": "用户名或密码错误。",
    "A daemon hibát adott:": "服务端返回错误：",
    "Feldolgozási hiba:": "响应处理失败：",
    "Nem sikerült megszerezni a session azonosítót.": "无法获取会话 ID。",
    "Kilépés": "退出",
    "Nagyítás": "放大",
    "Kicsinyítés": "缩小",
    "Eredeti méret": "实际大小",
    "Rendszer": "系统",
    "Nyelv": "语言",
    "Általános": "常规",
    "Szerverek": "服务器",
    "Sebesség": "速度",
    "Peerek": "节点",
    "Hálózat": "网络",
    "Sorok": "队列",
    "Letöltés": "下载",
    "Seedelés": "做种",

    // Sidebar and connection state
    "Szűrők": "筛选器",
    "Nincs kapcsolat": "未连接",
    "Nincs kapcsolat a szerverrel — a megnyitott torrentek a csatlakozás után kerülnek fel.": "未连接到服务器——打开的种子将在连接后添加。",
    "Csatlakozás…": "正在连接…",
    "Hiba": "错误",
    "Csatlakozva": "已连接",
    "Kiválasztva": "已选择",
    "Dock-ikon megjelenítése": "显示 Dock 图标",
    "Ablak előtérbe": "显示窗口",
    "Összes": "全部",
    "Letöltés alatt": "下载中",
    "Kész": "完成",
    "Aktív": "活动",
    "Inaktív": "空闲",
    "Leállítva": "已停止",
    "Hibás": "错误",
    "Szabad hely": "可用空间",
    "Nincs szerver — ⌘, a beállításokhoz": "没有服务器——按 ⌘, 打开设置",

    // Toolbar and torrent list
    "Turtle mód": "备用速度模式",
    "Alternatív sebességkorlát BE — kikapcsolás": "备用速度限制已开启——点击关闭",
    "Alternatív sebességkorlát (turtle) bekapcsolása": "开启备用速度限制",
    "Részletek panel megjelenítése/elrejtése (⌘I)": "显示/隐藏详细信息面板（⌘I）",
    "Név": "名称",
    "Állapot": "状态",
    "Méret": "大小",
    "Arány": "分享率",
    "Hozzáadva": "添加时间",
    "Utolsó aktivitás": "最后活动",
    "Befejezve": "完成时间",
    "Hátralévő": "剩余",
    "Alapértelmezett oszlopok": "默认列",
    "Frissítések keresése…": "检查更新…",
    "Elérhető új verzió": "有新版本可用",
    "Jelenlegi verzió": "当前版本",
    "Frissítés Homebrew-val:": "使用 Homebrew 更新：",
    "Kiadási oldal": "发布页面",
    "brew-parancs másolása": "复制 brew 命令",
    "Kihagyom ezt a verziót": "跳过此版本",
    "Később": "稍后",
    "A legfrissebb verziót használod": "已是最新版本",
    "Nem sikerült a frissítések keresése": "检查更新失败",
    "Új verzió": "新版本",
    "Frissítések": "更新",
    "Frissítések automatikus keresése (naponta)": "每天自动检查更新",
    "Keresés most": "立即检查",
    "Csak a GitHubtól kérdezi le a legfrissebb kiadás számát.": "仅从 GitHub 查询最新版本号。",
    "Adatvédelem": "隐私",
    "Névtelen használati statisztika küldése": "发送匿名使用统计",
    "Naponta egyszer: app-, macOS- és Transmission-verzió. Nincs azonosító, szervercím vagy torrent-adat.": "每天一次：发送应用、macOS 和 Transmission 版本。不包含标识符、服务器地址或种子数据。",
    "Letöltési sebesség": "下载速度",
    "Feltöltési sebesség": "上传速度",
    "A szerveren futó Transmission daemon verziója": "服务器上运行的 Transmission 服务端版本",

    // Empty states and details
    "Válassz szervert a Beállításokban (⌘,)": "请在设置中选择服务器（⌘,）",
    "Nincs torrent": "没有种子",
    "Ehhez a szűrőhöz nincs megjeleníthető torrent.": "没有符合此筛选条件的种子。",
    "Letöltve": "已下载",
    "Feltöltve": "已上传",
    "Letöltési ráta": "下载速率",
    "Feltöltési ráta": "上传速率",
    "Mappa": "文件夹",
    "Megjegyzés": "注释",
    "Nincs kijelölt torrent": "未选择种子",
    "Több torrent kijelölve": "已选择多个种子",
    "Fájlok": "文件",
    "Trackerek": "Tracker",
    "Összes tracker": "全部 Tracker",
    "Nincs fájlinformáció": "没有文件信息",
    "Alacsony": "低",
    "Normál": "普通",
    "Magas": "高",
    "Nincsenek kapcsolódott peerek": "没有已连接的节点",
    "Cím": "地址",
    "Kliens": "客户端",
    "Ország": "国家/地区",
    "Országadatok: DB-IP": "国家/地区数据：DB-IP",
    "Nincs tracker információ": "没有 Tracker 信息",
    "Seedek": "做种者",
    "Leecherek": "下载者",

    // Add / move / rename
    "Torrent hozzáadása": "添加 Torrent",
    "Magnet link vagy URL": "Magnet 链接或 URL",
    ".torrent fájl választása": "选择 .torrent 文件",
    "Leállítva add hozzá": "添加后暂停",
    "Szerver szerkesztése": "编辑服务器",
    "Új szerver": "新建服务器",
    "Hoszt": "主机",
    "RPC útvonal": "RPC 路径",
    "Felhasználónév (opcionális)": "用户名（可选）",
    "Jelszó (opcionális)": "密码（可选）",
    "mp": "秒",
    "perc": "分钟",
    "A művelet nem sikerült": "操作失败",
    "OK": "好",
    "Áthelyezés…": "移动…",
    "Átnevezés…": "重命名…",
    "Név másolása": "复制名称",
    "Hash másolása": "复制 Hash",
    "Torrent áthelyezése": "移动 Torrent",
    "kijelölt torrent": "个已选种子",
    "Célmappa a szerveren (abszolút útvonal)": "服务器上的目标文件夹（绝对路径）",
    "Fájlok átmozgatása": "移动文件",
    "A daemon átmozgatja a fájlokat az új helyre.": "服务端会将文件移动到新位置。",
    "Csak a nyilvántartott hely változik — a fájloknak már ott kell lenniük.": "只修改记录的位置——文件必须已经位于新位置。",
    "Áthelyezés": "移动",
    "Torrent átnevezése": "重命名 Torrent",
    "Új név": "新名称",
    "A daemon a letöltési mappában is átnevezi a fájlt/mappát. A név nem tartalmazhat „/” karaktert.": "服务端也会在下载文件夹中重命名文件或文件夹。名称不能包含“/”字符。",
    "Átnevezés": "重命名",

    // Rules
    "Szabályok": "规则",
    "Bekapcsolva": "已启用",
    "Az első illeszkedő szabály érvényesül, ezért a sorrend számít.": "第一条匹配的规则生效，因此顺序很重要。",
    "A szabálymotor ki van kapcsolva — új torrentekre nem fut le.": "规则引擎已关闭——不会应用于新添加的种子。",
    "Feljebb": "上移",
    "Lejjebb": "下移",
    "Új szabály": "新建规则",
    "Futtatás most…": "立即运行…",
    "Utolsó futás": "上次运行",
    "alkalmazva": "已应用",
    "sikertelen": "失败",
    "Szabály": "规则",
    "Szabály bekapcsolva": "启用规则",
    "Ha a": "如果",
    "Akkor": "则",
    "tracker-host": "Tracker 主机",
    "címke": "标签",
    "név-minta": "名称模式",
    "tracker": "Tracker",
    "név": "名称",
    "arány": "分享率",
    "üresjárat": "空闲",
    "leállítás": "停止",
    "nincs akció": "无操作",
    "Seed arány": "做种分享率",
    "Leállítás üresjárat után (perc)": "空闲（分钟）后停止",
    "Üresjárati limit (perc)": "空闲限制（分钟）",
    "Feltöltési korlát (KB/s)": "上传限速（KB/s）",
    "Letöltési korlát (KB/s)": "下载限速（KB/s）",
    "Feltöltési korlát": "上传限速",
    "Letöltési korlát": "下载限速",
    "Címke hozzáadása": "添加标签",
    "Azonnali leállítás": "立即停止",
    "Mit változtatna?": "将发生什么变化？",
    "Mit változtatna": "将发生什么变化",
    "Torrent": "Torrent",
    "Változás": "变化",
    "Alkalmazás": "应用",
    "Egyetlen torrenten sem változna semmi.": "没有任何种子会发生变化。",
    "Nem sikerült ellenőrizni a változásokat.": "无法检查变化。",
    "Biztosan törlöd a kijelölt torrent(eket)?": "确定要删除所选种子吗？",
    "Törlés a listából": "从列表中移除",
    "Törlés az adatokkal együtt": "连同数据一起删除",
    "Feltöltés": "上传",

    // Session settings
    "Sebességlimitek": "速度限制",
    "Alternatív sebesség (turbó)": "备用速度（加速）",
    "Peer-limitek": "节点限制",
    "Port": "端口",
    "Protokollok": "协议",
    "Titkosítás": "加密",
    "Sorkezelés": "队列管理",
    "Blokklista": "IP 黑名单",
    "Mappák": "文件夹",
    "Összes mappa": "全部文件夹",
    "Seedelési limitek": "做种限制",
    "Letöltési limit": "下载限制",
    "Feltöltési limit": "上传限制",
    "Maximális letöltési sebesség. Kikapcsolva korlátlan.": "最大下载速度。关闭时不限制。",
    "Maximális feltöltési sebesség. Kikapcsolva korlátlan.": "最大上传速度。关闭时不限制。",
    "Turbó mód aktív": "加速模式已启用",
    "A normál limitek helyett az alábbi alternatív sebességek érvényesek.": "将使用下面的备用速度，而不是常规限制。",
    "Alt. letöltés": "备用下载",
    "Alt. feltöltés": "备用上传",
    "Letöltési sebesség turbó módban.": "加速模式下的下载速度。",
    "Feltöltési sebesség turbó módban.": "加速模式下的上传速度。",
    "Időzített turbó": "定时加速",
    "A turbó mód automatikus be/kikapcsolása a megadott napszakban.": "在设定的时间段自动开启或关闭加速模式。",
    "Kezdés": "开始",
    "Vége": "结束",
    "A turbó mód kezdő időpontja (óra:perc).": "加速模式开始时间（时:分）。",
    "A turbó mód záró időpontja (óra:perc).": "加速模式结束时间（时:分）。",
    "Max. peer összesen": "最大节点总数",
    "Max. peer torrentenként": "每个种子的最大节点数",
    "Ennyi kliens (peer) csatlakozhat egyszerre, az összes torrenthez együttvéve.": "所有种子合计最多可同时连接的节点数。",
    "Egy adott torrenthez ennyi kliens csatlakozhat egyszerre.": "单个种子最多可同时连接的节点数。",
    "Peer port": "节点端口",
    "A bejövő kapcsolatokra figyelt port. Ezt kell átirányítani a routeren.": "用于监听传入连接的端口。需要在路由器上转发此端口。",
    "Véletlen port induláskor": "启动时随机选择端口",
    "A daemon minden indításkor véletlen portot választ (a fenti fix érték helyett).": "服务端每次启动时随机选择端口，而不是使用上面的固定端口。",
    "Port-továbbítás (UPnP/NAT-PMP)": "端口转发（UPnP/NAT-PMP）",
    "A router automatikus portnyitása. Jobb elérhetőség, ha a router támogatja.": "由路由器自动开放端口。如果路由器支持，可改善连通性。",
    "PEX (Peer Exchange)": "PEX（节点交换）",
    "Peerek cseréje a már kapcsolódó kliensekkel. Több elérhető peer.": "与已连接的客户端交换节点，可发现更多节点。",
    "DHT": "DHT",
    "Elosztott hash-tábla: peerek keresése tracker nélkül is.": "分布式哈希表：无需 Tracker 也能查找节点。",
    "LPD (helyi felfedezés)": "LPD（本地节点发现）",
    "Peerek keresése a helyi hálózaton (LAN).": "在局域网中发现节点。",
    "µTP": "µTP",
    "Micro Transport Protocol: forgalomszabályozás, hogy ne fojtsa meg a többi kapcsolatot.": "Micro Transport Protocol：调节流量，避免影响其他连接。",
    "Peer-titkosítás": "节点加密",
    "Kötelező: csak titkosított kapcsolat. Előnyben részesített: ha lehet, titkosít. Megengedő: elfogad titkosítatlant is.": "必须：仅允许加密连接。优先：尽可能加密。兼容：也接受未加密连接。",
    "Jelenleg használatban": "当前使用情况",
    "Aktív letöltések száma": "活动下载数",
    "Aktív seedelések száma": "活动做种数",
    "Az összes torrenten most csatlakozó kliensek száma a globális limithez képest.": "所有种子当前连接的客户端数量与全局限制的对比。",
    "Egyszerre letöltők korlátozása": "限制活动下载",
    "Ha be van kapcsolva, egyszerre csak ennyi torrent tölt aktívan, a többi sorban vár.": "开启后，同时只有指定数量的种子会活动下载，其余在队列中等待。",
    "A letöltési sorban egyszerre aktív torrentek maximuma.": "下载队列中同时活动的种子数上限。",
    "Egyszerre seedelők korlátozása": "限制活动做种",
    "Ha be van kapcsolva, egyszerre csak ennyi torrent seedel aktívan.": "开启后，同时只有指定数量的种子会活动做种。",
    "A seed sorban egyszerre aktív torrentek maximuma.": "做种队列中同时活动的种子数上限。",
    "Elakadtnak jelölés": "标记为停滞",
    "Ha egy torrent a megadott ideig nem forgalmaz, elakadtként kezeli (kikerül az aktív sorból).": "种子在指定时间内没有流量时，将被视为停滞并移出活动队列。",
    "Elakadtság ideje": "停滞时间",
    "Ennyi perc forgalommentesség után számít elakadtnak.": "无流量达到指定分钟数后视为停滞。",
    "Letöltési mappa": "下载文件夹",
    "A daemon ide menti a kész (és folyamatban lévő) letöltéseket. A daemon gépén értendő útvonal.": "服务端将已完成和进行中的下载保存到这里。路径指服务端上的路径。",
    "Befejezetlenek külön mappában": "未完成文件使用单独文件夹",
    "A folyamatban lévő letöltések egy külön ideiglenes mappába kerülnek, majd készen átmozgatja.": "进行中的下载放在单独的临时文件夹中，完成后再移动过去。",
    "Befejezetlenek mappája": "未完成文件夹",
    "A folyamatban lévő letöltések ideiglenes helye.": "进行中下载的临时位置。",
    "Befejezetlen fájlok „.part” végződése": "未完成文件使用“.part”后缀",
    "A még nem kész fájlok neve .part kiterjesztést kap, amíg le nem töltődnek.": "未完成的文件在下载完成前会使用 .part 扩展名。",
    "Azonnali indítás hozzáadáskor": "添加后立即开始",
    "A hozzáadott torrentek rögtön elindulnak (nem szüneteltetve kerülnek be).": "添加的种子会立即开始，而不是以暂停状态添加。",
    "Seedelés arány-limitig": "做种直到达到分享率限制",
    "A torrentek automatikus leállítása, ha elérik a megadott feltöltés/letöltés arányt.": "种子达到指定上传/下载分享率后自动停止。",
    "Cél feltöltési arány (pl. 2,0 = kétszer annyit tölt fel, mint le).": "目标上传分享率（例如 2.0 表示上传量达到下载量的两倍）。",
    "Leállítás tétlenség után": "空闲后停止",
    "A seedelés automatikus leállítása, ha a megadott ideig nincs aktivitás.": "一段时间没有活动后自动停止做种。",
    "Tétlenségi idő": "空闲时间",
    "Ennyi perc aktivitásmentesség után leáll a seedelés.": "无活动达到指定分钟数后停止做种。",
    "Blokklista aktív": "启用 IP 黑名单",
    "Ismert rosszindulatú/nem kívánt IP-tartományok tiltása.": "阻止已知的恶意或不需要的 IP 地址段。",
    "Blokklista URL": "IP 黑名单 URL",
    "A letöltendő blokklista címe.": "要下载的 IP 黑名单地址。",

    // Servers, streaming, RSS and statistics
    "Nincs szerver": "没有服务器",
    "Adj hozzá egy Transmission szervert a + gombbal.": "点击 + 按钮添加 Transmission 服务器。",
    "Szerver hozzáadása": "添加服务器",
    "Kijelölt szerver törlése": "删除所选服务器",
    "Egyéb műveletek": "更多操作",
    "Ellenőrzés (verify)": "校验",
    "Újrabejelentés a trackernek": "向 Tracker 重新汇报",
    "Streaming (sorrendi) letöltés be": "开启流式（顺序）下载",
    "Streaming letöltés ki": "关闭流式下载",
    "Sorrendi letöltéshez Transmission 4.1+ szükséges": "顺序下载需要 Transmission 4.1+",
    "a szerveren": "服务器",
    "ismeretlen": "未知",
    "Napok": "天",
    "Mely napokon lépjen életbe az időzített turbó.": "选择定时加速生效的日期。",
    "Sebességkorlát (erre a torrentre)": "速度限制（此种子）",
    "Alkalmaz": "应用",
    "Címkék": "标签",
    "Összes címke": "全部标签",
    "Új címke": "新标签",
    "Hozzáad": "添加",
    "Kliens-tanúsítvány (mTLS, opcionális)": "客户端证书（可选 mTLS）",
    ".p12 fájl útvonala": ".p12 文件路径",
    "Tallózás…": "浏览…",
    "Tanúsítvány jelszava": "证书密码",
    "RSS auto-letöltő": "RSS 自动下载",
    "Automatikus letöltés bekapcsolása": "启用自动下载",
    "Hírcsatornák (feed-ek)": "订阅源",
    "Nincs feed. Adj hozzá egyet lentebb.": "没有订阅源。请在下方添加。",
    "Feed URL": "订阅源 URL",
    "Szabályok (cím-szűrő)": "规则（标题筛选）",
    "Ha egy tétel címe illik egy aktív szabályra, automatikusan letöltődik. Szöveg = tartalmazás; /minta/ = regex.": "如果条目标题匹配活动规则，就会自动下载。普通文本表示包含；/模式/表示正则表达式。",
    "Új szabály (pl. 1080p vagy /S0[12]E../)": "新规则（例如 1080p 或 /S0[12]E../）",
    "Frissítés most": "立即检查",
    "Ellenőrzés 15 percenként": "每 15 分钟检查一次",
    "Statisztika": "统计",
    "Összes letöltve": "总下载量",
    "Összes feltöltve": "总上传量",
    "Aktív torrentek": "活动种子",
    "Alternatív („turbó”) sebesség": "备用速度（加速）",
    "Kliens-limitek": "客户端限制",
    "Peer-felfedezés": "节点发现",
    "Letöltési sor": "下载队列",
    "Seed sor": "做种队列",
    "Elakadt torrentek": "停滞种子",
    "Új torrentek": "新种子",
    "Arány-limit": "分享率限制",
    "Tétlen seedelés": "空闲做种",
    "Inaktivitás": "无活动",
    "szabály betöltve": "条规则已加载",
    "Elérted a globális peer-limitet — ha több kapcsolat kellene, emeld meg lentebb.": "已达到全局节点限制——如需更多连接，请提高下面的限制。",
    "Kötelező": "必须",
    "Előnyben részesített": "优先",
    "Megengedő": "兼容",
    "Tracker": "Tracker",
    "Torrent kész": "种子下载完成",
    "Success": "成功",
]


let simplifiedChinesePack = LanguagePack(
    title: "简体中文", localeIdentifier: "zh_CN", languageCodes: ["zh", "zh-Hans"],
    strings: simplifiedChineseStrings,
    statuses: [
        "Leállítva": "已停止",
        "Ellenőrzésre vár": "等待校验",
        "Ellenőrzés": "校验",
        "Letöltésre vár": "等待下载",
        "Letöltés": "下载中",
        "Seedelésre vár": "等待做种",
        "Seedelés": "做种中",
    ]
)
